# Generated by Django 5.1.6 on 2025-02-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(verbose_name='Body mass index')),
                ('diabetes', models.CharField(choices=[('No diabetes', 'No diabetes'), ('Prediabetes', 'Pre diabetes'), ('Diabetes', 'Diabetes')], max_length=20, verbose_name='Diabetes')),
                ('heartattack', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Heart attack')),
                ('stroke', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Stroke')),
                ('veggie', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Veggie')),
                ('fruits', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Fruits')),
                ('smoker', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Smoker')),
                ('alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Heavy alcohol consume')),
                ('highbp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='High blood pressure')),
                ('highchol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='High cholesterol')),
                ('diffwalk', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Difficulty walking')),
                ('physact', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Physical activity')),
                ('healtstatus', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=10, verbose_name='General health status')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Sex')),
                ('age', models.CharField(max_length=10, verbose_name='Age')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('form_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medpredapp.answersdb')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
    ]
