# Generated by Django 5.1.6 on 2025-02-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medpredapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersdb',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='answersdb',
            name='heartattack',
        ),
        migrations.RemoveField(
            model_name='answersdb',
            name='stroke',
        ),
    ]
