# Generated by Django 5.1.6 on 2025-02-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpredapp', '0002_remove_answersdb_diabetes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='form_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medpredapp.answersdb'),
        ),
    ]
